env:
  global:
    - secure: yEPR8Iu8N2JztkCMyggXD50Pj0bKK8SqKFqA0u/buj3Jul35+FNKDlphkFyjz0t0NgnKvReJQc4nIx08U5j8cAj1pNQDK6gmo3x/D444jWbSDGwTCGJy0rM3mLVWnB3RajfEJAo0tsF9XxB2Q08SM1skWhlJeuco9YmTFygjJ760aJxARcwMGWshDt2ueDXWssY8q5AEbs1gTMi8UpX/90T/0Im3Hw2qkptQ16ED6cnvYtVuDy+y17usfhDwOIuAI52YFblwRcwZylaDsEwl25athhHiCijmhVzozGS7iJzTHK6ItOnoT+lhaOWy1p0Hwf/1qEL82z1a3w8jAHMSYN476jbafjvYWew0hZxBUMiswHN/vaR30HTVxh9yFVaJoak/d1uUGj314PYK8VRjxKMjqg5GDAJ2dzYQT+Jw9mW9y1GVe8UthfpXPHWC3SSpOIchYb8gkgYrmjuLqFkbFA6Ptx8acP0JN7KrY7HvXf//+pGGyErl/xe1t6tGjQocAgo3W9Dg/amuKfl/Faoo2YRwyZpVm3SNmv8DVrMO89AL28Pnk10dqnPN2nvDmMhB4uEVuhjfqfWEJZjtrQHVaqCzJb1avkIayR5iulQVhJQ5MLUBB434ZaF37JhM+X4dST9snH1IuiRHsQf/GCDpA2K78ouy77mnhYIjKsSqllE=
    - secure: SLrtCGamwqmOZum7BLMCbk9NZHkY9iB86bLPOSDD7x7IUum0ZKSh+N/T0dhqGUMiRVocKGNs6HQ9vhrOs3R1zFhn8M+A4kIhOoxb+dXm2nDys5FY00U6O8k8vuJ7LDx2/syYqoO7Xlr1au1uffl4e3xvkgETZnJ3CAN+aj9SPNwHW3gFQzqrRCplVXqmUVMhiFFycn36Y6tyQ3tBccNCLcKA60bERh5hXp/MUuPCQntZWFw4r8WsU/LL+460Ks29adN1fk9GeaHYKzL5nFgkrwhCz48059wGrcCafPMlWqVP1kAQsRfPLWz2t4eBBl0d7wz+WggppAfwsAu0yzNftnj5BY3Pmfbj5xSIluFNHBKLy/qoqFzkd90IJNOCzz+ngSRiUSng54Ds1TsyHgM+GXkd7ajyrkrwJFyWs42In94j4hCvouu35sON2bC+Ub88YLb/4mLn+g+gxYb898AJhA/mfw+WC531/YS5pNWeLEq9+D5QFXisTws+j9SvsycfBPb+ObeqiJhZersSyQPpsZNu8AEOyVQ/EaQ7sWafbYXH6iB4ttd3oojg/EuF3uPK/UOPwG1s6sbGtuVkXjLXZJb9rP2XNH5m6YqXh/MVsfRXuLeaNpIM3VGx+t2Nl5+jjmRs83/+QRnv6rbLzxnizpm3gdFkns+hSE4qZBjGvHQ=
addons:
  sauce_connect: true
language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
